# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'avatars'),
        ),
    ]
