# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20160830_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=b'img/'),
        ),
    ]
