# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=None),
        ),
    ]
