# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20160831_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=b'avatars/'),
        ),
    ]
